version: '2'

services:
  data-warehouses-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: data-warehouses-sql
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123!
    volumes:
      - data-warehouses-sql_data:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  data-warehouses-sql_data:
    name: data-warehouses-sql_data
    driver: local